source/accounts/urls.py
from django.urls import path

from .views import (login_view, logout_view, UserView,
                    RegisterView, UserUpdateView, UserPasswordChangeView,
                    SearchResultView)


app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserView.as_view(), name='profile'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/update', UserUpdateView.as_view(), name='edit_profile'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
    path('search_result/', SearchResultView.as_view(), name='search_result'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from .views import PublicationViewSet, LogoutView


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'publications', PublicationViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
 ]

source/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (permission_denied, PublicationCreateView, PublicationView, SubscriptionCreateView,
                    SubscribersListView, SubscribitionsListView, LikeCreateView, CommentCreateView)


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='index'),
    path('403/', permission_denied, name='403'),
    path('profile/<int:pk>/new_publication/', PublicationCreateView.as_view(), name='new_publication'),
    path('profile/<int:pk>/details', PublicationView.as_view(), name='publication_details'),
    path('subscription/<int:pk>/', SubscriptionCreateView.as_view(), name='subscription'),
    path('subscribers/<int:pk>/', SubscribersListView.as_view(), name='subscribers'),
    path('subscribitions/<int:pk>/', SubscribitionsListView.as_view(), name='subscribitions'),
    path('like/<int:pk>/', LikeCreateView.as_view(), name='like'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='new_comment'),
]

source/accounts/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser


gender_choices = [('m', 'Man'), ('w', 'Woman')]


class AppUser(AbstractUser):
    email = models.EmailField(max_length=30, unique=True, null=False, blank=False, verbose_name="Email")
    avatar = models.ImageField(upload_to='user_pics', verbose_name='Avatar')
    bio = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Bio")
    phone = models.CharField(max_length=15, null=True, blank=True, verbose_name="Phone number")
    gender = models.CharField(max_length=30, null=True, blank=True, verbose_name='Gender', choices=gender_choices)
    publications_count = models.IntegerField(default=0, verbose_name='Publications')
    subscriptions_count = models.IntegerField(default=0, verbose_name='Subscriptions')
    subscribers_count = models.IntegerField(default=0, verbose_name='Subscribers')

    def increase_count(self, marker):
        match marker:
            case 'publications':
                self.publications_count += 1
            case 'subscriptions':
                self.subscriptions_count += 1
            case 'subscribers':
                self.subscribers_count += 1
        self.save()

    def __str__(self):
        return f'{self.first_name} {self.last_name}, username: {self.username}'

    def get_absolute_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.pk})

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username', 'email', 'avatar',
            'bio', 'first_name', 'last_name',
            'phone', 'gender'
        )

source/accounts/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import login, logout, get_user_model
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.utils.http import urlencode

from .auth import EmailUsernameAuthentication as EUA
from .forms import UserForm
from webapp.forms import SearchForm
from webapp.models import Subscription, Publication


User_model = get_user_model()


def login_view(request):
    context = {}
    context['search_form'] = SearchForm(request.GET)
    if request.user.is_authenticated:
        user = get_object_or_404(User_model, pk=request.user.pk)
        subscribe = Subscription.objects.filter(user=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.subscriber.pk)
            context['subscribitions_publications'] = Publication.objects.filter(author__in=subscribitions_pk).order_by('-created_at')
    if request.method == 'POST':
        login_data = request.POST.get('login_data')
        password = request.POST.get('password')
        user = EUA.authenticate(request, login_data, password)
        if user is not None:
            login(request, user)
            return redirect('accounts:login')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')


class UserView(DetailView):
    model = User_model
    template_name = 'profile.html'
    context_object_name = 'user_obj'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['publications'] = self.object.publications.all()
        context['search_form'] = SearchForm(self.request.GET)
        if self.request.user.pk != self.kwargs.get('pk'):
            user_from_profile = User_model.objects.get(pk=self.kwargs.get('pk'))
            subscribe = Subscription.objects.filter(user=self.request.user, subscriber=user_from_profile)
            if subscribe:
                context['subscribe'] = True
        return context


class RegisterView(CreateView):
    model = get_user_model()
    form_class = UserForm
    template_name = 'registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_page = reverse('accounts:login')
        return next_page


class UserUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'edit_profile.html'
    model = User_model
    form_class = UserForm

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        return redirect('webapp:403')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context


class UserPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        return redirect('webapp:403')

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context


class SearchResultView(ListView):
    model = User_model
    template_name = 'users_list.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(username__icontains=self.search_value) |
                Q(email__icontains=self.search_value) |
                Q(first_name__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context

source/accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit profile{% endblock %}
{% block content %}
    <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold me-1 mb-1" href="{% url 'accounts:profile' pk=request.user.pk %}">Back to profile</a>
    {% include 'partial/form.html' with value_submit='Edit profile' form_method='post' enctype='multipart/form-data' %}
{% endblock %}

source/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Log in{% endblock %}
{% block content %}
    {% if not request.user.is_authenticated %}
        <h1>Log in</h1>
        <form class="mb-2" action="{% url 'accounts:login' %}" method="POST" id="loginForm">
            {% csrf_token %}
            {% if has_error %}
                <p class="form-error">Wrong email/username or password</p>
            {% endif %}
            <div class="form-group">
                <label for="login_data" class="form-label">Username/email:</label>
                <input type="text" name="login_data" id="login_data">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" id="password">
            </div>
            <button type="submit">Submit</button>
        </form>
        <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold" href="{% url 'accounts:registration' %}">Create new...</a>
    {% endif %}
    {% if request.user.is_authenticated %}
        <form id="logout-form" method="POST" action="{% url 'accounts:logout' %}" class="mb-1">
            {% csrf_token %}
            <button type="submit">Log out</button>
        </form>
        {% for publication in subscribitions_publications %}
            <div class="card mb-1">
                <img src="{{ publication.img.url }}" class="card-img-top" alt="avatar" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ publication.author }}</h5>
                    <p class="card-text">{{ publication.content }}, {{ publication.created_at }}</p>
                    <p class="card-text"><small><a href="{% url 'webapp:publication_details' pk=publication.pk %}" class="nav-link">Go to publication...</a></small></p>
                </div>
            </div>
        {% empty %}
            <p>No publications</p>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block script %}
    <script>
        async function makeRequest(url, method='GET', data={}, token=null) {
            let headers = {
                "Content-Type": "application/json"
            };
            if (token) {
                headers['Authorization'] = 'Token ' + token;
            }
            let body = JSON.stringify(data);
            let response = await fetch(url, {method, headers, body: JSON.stringify(data)});
            if (response.ok) {  // нормальный ответ
                return await response.json();
            } else {            // ошибка
                let error = new Error(response.statusText);
                error.response = response;
                throw error;
            }
        }

        async function onSubmit(e) {
            e.preventDefault();
            console.log(e.target);
            let username = e.target.login_data.value;
            let password = e.target.password.value;
            try {
                let response = await makeRequest(
                'http://127.0.0.1:8000/api/login/',
                "POST",
                {
                 "username": username,
                 "password": password
                 }
                );
                console.log(response);
                localStorage.setItem('apiToken', response.token);
            } finally {
                e.target.submit();
            }
        }

        async function onLoad() {
            let loginForm = document.getElementById('loginForm');
            loginForm.addEventListener('submit', onSubmit);

        }

        window.addEventListener('load', onLoad);
    </script>
{% endblock %}

source/accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ request.user.first_name }} {{ request.user.last_name }}'s profile{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12 col-md-4 mb-1">
            <div class="user-logo">
                {% if user_obj.avatar %}
                    <img class="image" src="{{ user_obj.avatar.url }}">
                {% else %}
                    <span>No avatar</span>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-8">
            <div class="d-flex justify-content-between mb-2">
                <h1 class="display-6 me-1">{{ user_obj.username }}</h1>
                {% if request.user.is_authenticated and request.user == user_obj %}
                    <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold me-1" href="{% url 'accounts:edit_profile' pk=request.user.pk %}">Edit profile</a>
                    <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold" href="{% url 'accounts:user_password_change' request.user.pk %}">Change password</a>
                {% endif %}
                {% if request.user.is_authenticated and request.user != user_obj %}
                    {% if not subscribe %}
                        <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold me-1" href="{% url 'webapp:subscription' pk=user_obj.pk %}">Subscribe</a>
                    {% else %}
                        <p>You're already subscribe to this user!</p>
                    {% endif %}
                {% endif %}
            </div>
            <div class="d-flex justify-content-between mb-2">
                <span class="me-1">{{ user_obj.publications_count }} publications</span>
                <a class="me-1" href="{% url 'webapp:subscribitions' pk=user_obj.pk %}">{{ user_obj.subscriptions_count }} subscriptions</a>
                <a href="{% url 'webapp:subscribers' pk=user_obj.pk %}">{{ user_obj.subscribers_count }} subscribers</a>
            </div>
            <p class="fw-bold">{{ user_obj.last_name }} {{ user_obj.first_name }}</p>
            <p>{{ user_obj.bio }}</p>
        </div>
    </div>
    <hr>
     <div class="row row-cols-1 row-cols-md-3 publications">
        {% for publication in publications %}
            {% include 'partial/publications.html' %}
        {% endfor %}
        {% if request.user.is_authenticated and request.user == user_obj %}
             <div class="col align-self-stretch">
                <div class="card">
                    <a href="{% url 'webapp:new_publication' pk=user_obj.pk %}" class="m-auto">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                        </svg>
                    </a>
                </div>
             </div>
         {% endif %}
    </div>
{% endblock %}

source/accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registration{% endblock %}
{% block content %}
    <h1>Registration</h1>
    <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold me-1 mb-1" href="{% url 'accounts:login' %}">Back to welcome page</a>
    {% include 'partial/form.html' with value_submit='Registration' form_method='post' enctype='multipart/form-data' %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Change password{% endblock %}
{% block content %}
    <h1>Change password</h1>
    <a type="button" class="btn btn-light border border-black w-75 py-3 fw-bold me-1 mb-1" href="{% url 'accounts:profile' pk=request.user.pk %}">Back to profile</a>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" value_submit='Change password' %}
{% endblock %}

source/accounts/templates/users_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Users</h1>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% for user in user_obj %}
        <div class="card">
            <img src="{{ user.avatar.url }}" class="card-img-top" alt="avatar" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ user.username }}</h5>
                <p class="card-text">{{ user.email }}, {{ user.first_name }} {{ user.last_name }}</p>
                <p class="card-text"><small><a href="{% url 'accounts:profile' pk=user.pk %}" class="nav-link">Go to profile...</a></small></p>
            </div>
        </div>
    {% empty %}
        <p>No users</p>
    {% endfor %}
{% endblock %}