source/accounts/urls.py
from django.urls import path

from .views import (login_view, logout_view, UserView,
                    RegisterView, UserUpdateView, UserPasswordChangeView,
                    SearchResultView)


app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserView.as_view(), name='profile'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/update', UserUpdateView.as_view(), name='edit_profile'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
    path('search_result/', SearchResultView.as_view(), name='search_result'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from .views import PublicationViewSet, LogoutView


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'publications', PublicationViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
 ]

source/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (permission_denied, PublicationCreateView, PublicationView, SubscriptionCreateView,
                    SubscribersListView, SubscribitionsListView, LikeCreateView, CommentCreateView)


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='index'),
    path('403/', permission_denied, name='403'),
    path('profile/<int:pk>/new_publication/', PublicationCreateView.as_view(), name='new_publication'),
    path('profile/<int:pk>/details', PublicationView.as_view(), name='publication_details'),
    path('subscription/<int:pk>/', SubscriptionCreateView.as_view(), name='subscription'),
    path('subscribers/<int:pk>/', SubscribersListView.as_view(), name='subscribers'),
    path('subscribitions/<int:pk>/', SubscribitionsListView.as_view(), name='subscribitions'),
    path('like/<int:pk>/', LikeCreateView.as_view(), name='like'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='new_comment'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name="Created at", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        abstract = True


class Publication(AbstractModel):
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Content")
    author = models.ForeignKey(get_user_model(), default=1, related_name='publications', on_delete=models.CASCADE, verbose_name="Author")
    img = models.ImageField(upload_to='publications_images', verbose_name='Avatar')
    likes_count = models.IntegerField(default=0, verbose_name='Count of likes')
    comments_count = models.IntegerField(default=0, verbose_name='Count of comments')

    def increase_count(self, marker):
        match marker:
            case 'likes':
                self.likes_count += 1
            case 'comments':
                self.comments_count += 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_subscribers',
        on_delete=models.CASCADE, verbose_name='User'
    )
    subscriber = models.ForeignKey(
        get_user_model(), related_name='subscriber_users',
        on_delete=models.CASCADE, verbose_name='Subscriber'
    )


class Like(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_publications',
        on_delete=models.CASCADE, verbose_name='User'
    )
    publication = models.ForeignKey(
        Publication, related_name='publication_users',
        on_delete=models.CASCADE, verbose_name='Publication'
    )


class Comment(AbstractModel):
   publication = models.ForeignKey(
       'webapp.Publication', related_name='comments',
       on_delete=models.CASCADE, verbose_name='Comment'
   )
   text = models.TextField(max_length=400, verbose_name='Comment')
   author = models.ForeignKey(
       get_user_model(), related_name='comments',
       on_delete=models.CASCADE, verbose_name="Author"
   )

source/webapp/forms.py
from django import forms
from django.forms import widgets

from .models import Publication, Comment


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Find', widget=widgets.Input(attrs={'class': 'form-control'}))


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ('content', 'img', )
        error_messages = {
            'content': {
                'required': 'Please enter title',
            }
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

source/webapp/views.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/comments.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView

from ..models import Comment, Publication
from ..forms import CommentForm


class CommentCreateView(CreateView):
    template_name = 'comments/comment_create.html'
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.publication = publication
        comment.author = self.request.user
        comment.save()
        publication.increase_count('comments')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/errors.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/like.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404

from ..models import Publication, Like


class LikeCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        publication = get_object_or_404(Publication, pk=kwargs.get('pk'))
        like = Like.objects.filter(user=user, publication=publication)
        if not like:
            Like.objects.create(user=user, publication=publication)
            publication.increase_count('likes')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/publications.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin

from ..models import Publication, Like, Comment
from ..forms import PublicationForm, SearchForm


class PublicationCreateView(UserPassesTestMixin, CreateView):
    template_name = 'publications/new.html'
    model = Publication
    form_class = PublicationForm

    def form_valid(self, form):
        publication = form.save(commit=False)
        publication.author = self.request.user
        publication.save()
        publication.author.increase_count('publications')
        # return redirect('webapp:publication', pk=publication.pk)
        return redirect('accounts:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        return redirect('webapp:403')


class PublicationView(DetailView):
    model = Publication
    template_name = 'publications/details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        like = Like.objects.filter(user=self.request.user, publication=publication)
        if not like:
            context['like'] = False
        else:
            context['like'] = True
        comments = Comment.objects.filter(publication=publication)
        context['comments'] = comments
        return context

source/webapp/views/subscription.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView

from ..models import Subscription, Publication
from ..forms import SearchForm
from accounts.views import User_model


class SubscriptionCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        subscriber = get_object_or_404(User_model, pk=kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user, subscriber=subscriber)
        if not subscribe and user != subscriber:
            Subscription.objects.create(user=user, subscriber=subscriber)
            request.user.increase_count('subscriptions')
            subscriber.increase_count('subscribers')
        return redirect('accounts:profile', pk=subscriber.pk)


class SubscribersListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribers.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(subscriber=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.user.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context


class SubscribitionsListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribitions.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.subscriber.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

source/webapp/templates/partial/base_menu.html
{% if request.user.is_authenticated %}
    <div class="d-flex w-100 justify-content-center">
    <div class="nav-link mx-auto">
        {% include 'partial/search.html' %}
    </div>
    <a href="{% url 'accounts:profile' pk=request.user.pk %}" class="nav-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
        </svg>
    </a>
    </div>
{% endif %}

source/webapp/templates/partial/form.html
<form action="{{ action_url }}" method="{{ form_method }}"  enctype="{{ enctype }}">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {% for field in form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}:</label><br/>
        {{ field }}<br/>
        {% for error in field.errors %}
            <p class="tex-danger">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <br/>
    <input class="btn btn-light border border-black" type="submit" value="{{ value_submit }}"/>
</form>

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                <input type="hidden" name="search" value="{{ search_value }}">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/publications.html
<div class="col mb-2">
    <div class="card">
        <a href="{% url 'webapp:publication_details' pk=publication.pk %}">
            <img src="{{ publication.img.url }}" class="img-fluid" alt="photo{{ publication.pk }}" style="width: 100%">
        </a>
    </div>
</div>

source/webapp/templates/partial/search.html
<form class="text-center" action="{% url 'accounts:search_result' %}" method="GET">
    <div class="input-group flex-nowrap">
        <span class="input-group-text" id="addon-wrapping">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
            </svg>
        </span>
        {{ search_form.search }}
    </div>
</form>

source/webapp/templates/partial/users_data.html
<div class="card">
    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" class="card-img-top" alt="avatar" style="width: 18rem;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ user.username }}</h5>
        <p class="card-text">{{ user.email }}, {{ user.first_name }} {{ user.last_name }}</p>
        <p class="card-text"><small><a href="{% url 'accounts:profile' pk=user.pk %}" class="nav-link">Go to profile...</a></small></p>
    </div>
</div>