source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from .views import PublicationViewSet, LogoutView


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'publications', PublicationViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
 ]

source/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (permission_denied, PublicationCreateView, PublicationView, SubscriptionCreateView,
                    SubscribersListView, SubscribitionsListView, LikeCreateView, CommentCreateView)


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='index'),
    path('403/', permission_denied, name='403'),
    path('profile/<int:pk>/new_publication/', PublicationCreateView.as_view(), name='new_publication'),
    path('profile/<int:pk>/details', PublicationView.as_view(), name='publication_details'),
    path('subscription/<int:pk>/', SubscriptionCreateView.as_view(), name='subscription'),
    path('subscribers/<int:pk>/', SubscribersListView.as_view(), name='subscribers'),
    path('subscribitions/<int:pk>/', SubscribitionsListView.as_view(), name='subscribitions'),
    path('like/<int:pk>/', LikeCreateView.as_view(), name='like'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='new_comment'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name="Created at", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        abstract = True


class Publication(AbstractModel):
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Content")
    author = models.ForeignKey(get_user_model(), default=1, related_name='publications', on_delete=models.CASCADE, verbose_name="Author")
    img = models.ImageField(upload_to='publications_images', verbose_name='Avatar')
    likes_count = models.IntegerField(default=0, verbose_name='Count of likes')
    comments_count = models.IntegerField(default=0, verbose_name='Count of comments')

    def increase_count(self, marker):
        match marker:
            case 'likes':
                self.likes_count += 1
            case 'comments':
                self.comments_count += 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_subscribers',
        on_delete=models.CASCADE, verbose_name='User'
    )
    subscriber = models.ForeignKey(
        get_user_model(), related_name='subscriber_users',
        on_delete=models.CASCADE, verbose_name='Subscriber'
    )


class Like(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_publications',
        on_delete=models.CASCADE, verbose_name='User'
    )
    publication = models.ForeignKey(
        Publication, related_name='publication_users',
        on_delete=models.CASCADE, verbose_name='Publication'
    )


class Comment(AbstractModel):
   publication = models.ForeignKey(
       'webapp.Publication', related_name='comments',
       on_delete=models.CASCADE, verbose_name='Comment'
   )
   text = models.TextField(max_length=400, verbose_name='Comment')
   author = models.ForeignKey(
       get_user_model(), related_name='comments',
       on_delete=models.CASCADE, verbose_name="Author"
   )

source/webapp/forms.py
from django import forms
from django.forms import widgets

from .models import Publication, Comment


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Find', widget=widgets.Input(attrs={'class': 'form-control'}))


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ('content', 'img', )
        error_messages = {
            'content': {
                'required': 'Please enter title',
            }
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

source/webapp/views.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/comments.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView

from ..models import Comment, Publication
from ..forms import CommentForm


class CommentCreateView(CreateView):
    template_name = 'comments/comment_create.html'
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.publication = publication
        comment.author = self.request.user
        comment.save()
        publication.increase_count('comments')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/errors.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/like.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404

from ..models import Publication, Like


class LikeCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        publication = get_object_or_404(Publication, pk=kwargs.get('pk'))
        like = Like.objects.filter(user=user, publication=publication)
        if not like:
            Like.objects.create(user=user, publication=publication)
            publication.increase_count('likes')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/publications.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin

from ..models import Publication, Like, Comment
from ..forms import PublicationForm, SearchForm


class PublicationCreateView(UserPassesTestMixin, CreateView):
    template_name = 'publications/new.html'
    model = Publication
    form_class = PublicationForm

    def form_valid(self, form):
        publication = form.save(commit=False)
        publication.author = self.request.user
        publication.save()
        publication.author.increase_count('publications')
        # return redirect('webapp:publication', pk=publication.pk)
        return redirect('accounts:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        return redirect('webapp:403')


class PublicationView(DetailView):
    model = Publication
    template_name = 'publications/details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        like = Like.objects.filter(user=self.request.user, publication=publication)
        if not like:
            context['like'] = False
        else:
            context['like'] = True
        comments = Comment.objects.filter(publication=publication)
        context['comments'] = comments
        return context

source/webapp/views/subscription.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView

from ..models import Subscription, Publication
from ..forms import SearchForm
from accounts.views import User_model


class SubscriptionCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        subscriber = get_object_or_404(User_model, pk=kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user, subscriber=subscriber)
        if not subscribe and user != subscriber:
            Subscription.objects.create(user=user, subscriber=subscriber)
            request.user.increase_count('subscriptions')
            subscriber.increase_count('subscribers')
        return redirect('accounts:profile', pk=subscriber.pk)


class SubscribersListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribers.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(subscriber=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.user.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context


class SubscribitionsListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribitions.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.subscriber.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

source/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Instagram task{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'webapp:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                    </svg>
                </a>
                <div class="d-flex justify-content-around align-items-center">
                    <span class="menu-line me-2">|</span>
                    <span class="lobster-regular mt-1 me-2">Instagram</span>
                </div>
                {% if request.user.is_authenticated %}
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                {% endif %}
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav w-100">
                        {% block menu %}
                            {% include 'partial/base_menu.html' %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </nav>
        {% if request.user.is_authenticated %}
            <p>You entered as {{ request.user }}</p>
        {% endif %}
        <div class="container roboto-thin">
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

        {% block script %}
        {% endblock %}
    </body>
</html>