source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from .views import PublicationViewSet, LogoutView


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'publications', PublicationViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
 ]

source/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (permission_denied, PublicationCreateView, PublicationView, SubscriptionCreateView,
                    SubscribersListView, SubscribitionsListView, LikeCreateView, CommentCreateView)


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='index'),
    path('403/', permission_denied, name='403'),
    path('profile/<int:pk>/new_publication/', PublicationCreateView.as_view(), name='new_publication'),
    path('profile/<int:pk>/details', PublicationView.as_view(), name='publication_details'),
    path('subscription/<int:pk>/', SubscriptionCreateView.as_view(), name='subscription'),
    path('subscribers/<int:pk>/', SubscribersListView.as_view(), name='subscribers'),
    path('subscribitions/<int:pk>/', SubscribitionsListView.as_view(), name='subscribitions'),
    path('like/<int:pk>/', LikeCreateView.as_view(), name='like'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='new_comment'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name="Created at", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        abstract = True


class Publication(AbstractModel):
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Content")
    author = models.ForeignKey(get_user_model(), default=1, related_name='publications', on_delete=models.CASCADE, verbose_name="Author")
    img = models.ImageField(upload_to='publications_images', verbose_name='Avatar')
    likes_count = models.IntegerField(default=0, verbose_name='Count of likes')
    comments_count = models.IntegerField(default=0, verbose_name='Count of comments')

    def increase_count(self, marker):
        match marker:
            case 'likes':
                self.likes_count += 1
            case 'comments':
                self.comments_count += 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_subscribers',
        on_delete=models.CASCADE, verbose_name='User'
    )
    subscriber = models.ForeignKey(
        get_user_model(), related_name='subscriber_users',
        on_delete=models.CASCADE, verbose_name='Subscriber'
    )


class Like(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='user_publications',
        on_delete=models.CASCADE, verbose_name='User'
    )
    publication = models.ForeignKey(
        Publication, related_name='publication_users',
        on_delete=models.CASCADE, verbose_name='Publication'
    )


class Comment(AbstractModel):
   publication = models.ForeignKey(
       'webapp.Publication', related_name='comments',
       on_delete=models.CASCADE, verbose_name='Comment'
   )
   text = models.TextField(max_length=400, verbose_name='Comment')
   author = models.ForeignKey(
       get_user_model(), related_name='comments',
       on_delete=models.CASCADE, verbose_name="Author"
   )

source/webapp/forms.py
from django import forms
from django.forms import widgets

from .models import Publication, Comment


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Find', widget=widgets.Input(attrs={'class': 'form-control'}))


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ('content', 'img', )
        error_messages = {
            'content': {
                'required': 'Please enter title',
            }
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

source/webapp/views.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/comments.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView

from ..models import Comment, Publication
from ..forms import CommentForm


class CommentCreateView(CreateView):
    template_name = 'comments/comment_create.html'
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.publication = publication
        comment.author = self.request.user
        comment.save()
        publication.increase_count('comments')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/errors.py
from django.shortcuts import render


def permission_denied(request):
    return render(request, 'errors/403.html', status=403)

source/webapp/views/like.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404

from ..models import Publication, Like


class LikeCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        publication = get_object_or_404(Publication, pk=kwargs.get('pk'))
        like = Like.objects.filter(user=user, publication=publication)
        if not like:
            Like.objects.create(user=user, publication=publication)
            publication.increase_count('likes')
        return redirect('webapp:publication_details', pk=publication.pk)

source/webapp/views/publications.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin

from ..models import Publication, Like, Comment
from ..forms import PublicationForm, SearchForm


class PublicationCreateView(UserPassesTestMixin, CreateView):
    template_name = 'publications/new.html'
    model = Publication
    form_class = PublicationForm

    def form_valid(self, form):
        publication = form.save(commit=False)
        publication.author = self.request.user
        publication.save()
        publication.author.increase_count('publications')
        # return redirect('webapp:publication', pk=publication.pk)
        return redirect('accounts:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        return redirect('webapp:403')


class PublicationView(DetailView):
    model = Publication
    template_name = 'publications/details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        publication = get_object_or_404(Publication, pk=self.kwargs.get('pk'))
        like = Like.objects.filter(user=self.request.user, publication=publication)
        if not like:
            context['like'] = False
        else:
            context['like'] = True
        comments = Comment.objects.filter(publication=publication)
        context['comments'] = comments
        return context

source/webapp/views/subscription.py
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView

from ..models import Subscription, Publication
from ..forms import SearchForm
from accounts.views import User_model


class SubscriptionCreateView(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        user = self.request.user
        subscriber = get_object_or_404(User_model, pk=kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user, subscriber=subscriber)
        if not subscribe and user != subscriber:
            Subscription.objects.create(user=user, subscriber=subscriber)
            request.user.increase_count('subscriptions')
            subscriber.increase_count('subscribers')
        return redirect('accounts:profile', pk=subscriber.pk)


class SubscribersListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribers.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(subscriber=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.user.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context


class SubscribitionsListView(ListView):
    model = User_model
    template_name = 'subscribition/subscribitions.html'
    context_object_name = 'user_obj'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('username',)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('webapp:403')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        user = get_object_or_404(User_model, pk=self.kwargs.get('pk'))
        subscribe = Subscription.objects.filter(user=user)
        if subscribe:
            subscribitions_pk = []
            for subscribition in subscribe:
                subscribitions_pk.append(subscribition.subscriber.pk)
            queryset = queryset.filter(pk__in=subscribitions_pk)
        else:
            queryset = []
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = SearchForm(self.request.GET)
        return context

source/webapp/templates/publications/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ publication.id }} details{% endblock %}
{% block content %}
    <h1>{{ publication.id }} details</h1>
    <div class="card mb-2">
        <img src="{{ publication.img.url }}" class="card-img-top" alt="avatar">
        <div class="card-body">
            <p class="card-text">
                {% if not like %}
                    <button type="button" class="nav-link publication_like" data-like="like" data-url="{% url 'api:publication-detail' publication.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                        </svg></button>
                {% else %}
                    <button type="button" class="nav-link publication_like" data-like="unlike" data-url="{% url 'api:publication-detail' publication.pk %}" data-count-id="{{ publication.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-through-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2.854 15.854A.5.5 0 0 1 2 15.5V14H.5a.5.5 0 0 1-.354-.854l1.5-1.5A.5.5 0 0 1 2 11.5h1.793l3.103-3.104a.5.5 0 1 1 .708.708L4.5 12.207V14a.5.5 0 0 1-.146.354zM16 3.5a.5.5 0 0 1-.854.354L14 2.707l-1.006 1.006c.236.248.44.531.6.845.562 1.096.585 2.517-.213 4.092-.793 1.563-2.395 3.288-5.105 5.08L8 13.912l-.276-.182A24 24 0 0 1 5.8 12.323L8.31 9.81a1.5 1.5 0 0 0-2.122-2.122L3.657 10.22a9 9 0 0 1-1.039-1.57c-.798-1.576-.775-2.997-.213-4.093C3.426 2.565 6.18 1.809 8 3.233c1.25-.98 2.944-.928 4.212-.152L13.292 2 12.147.854A.5.5 0 0 1 12.5 0h3a.5.5 0 0 1 .5.5z"/>
                        </svg></button>
                {% endif %} <span id="count">{{ publication.likes_count }}</span> likes
            </p>
            <p class="card-text">
                <a href="{% url 'webapp:new_comment' pk=publication.pk %}" class="nav-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                    </svg> {{ publication.comments_count }} comments
                </a>
            </p>
            <p class="card-text">{{ publication.content }}</p>
            <p class="card-text">{{ publication.author }}</p>
        </div>
    </div>
    <div>
        <ul class="list-group">
        {% for comment in comments %}
            <li class="list-group-item">{{ comment.text }}<br>{{ comment.author }}<br>{{ comment.created_at }}</li>
        {% empty %}
            <li class="list-group-item">No comments</li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block script %}
    <script>
        async function makeRequest(url, method='GET', data={}, token=null) {
            let headers = {
                "Content-Type": "application/json"
            };
            if (token) {
                headers['Authorization'] = 'Token ' + token;
            }
            let body = JSON.stringify(data);
            let response = await fetch(url, {method, headers, body: JSON.stringify(data)});
            if (response.ok) {  // нормальный ответ
                return await response.json();
            } else {            // ошибка
                let error = new Error(response.statusText);
                error.response = response;
                throw error;
            }
        }

        async function onClick(e) {
            e.preventDefault();
            let d = e.currentTarget.dataset['like'];
            let url = e.currentTarget.dataset['url'] + `${d}/`;
            let span_count = document.getElementById('count');
            let method = 'POST';
            if (d == 'unlike') {
                method = 'DELETE';
                e.currentTarget.dataset['like'] = "like";
            } else {
                e.currentTarget.dataset['like'] = "unlike";
            }

            let response = await makeRequest(
                url,
                method,
                {},
                localStorage.getItem('apiToken')
            );
            span_count.innerText = response.likes_count;
        }

        async function onLoad() {
            let buttons = document.getElementsByClassName('publication_like');
            for (let button of buttons) {
                button.addEventListener('click', onClick);
            }

        }

        window.addEventListener('load', onLoad);
    </script>
{% endblock %}

source/webapp/templates/publications/new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add new publication{% endblock %}
{% block content %}
    <h1>New publication</h1>
    {% include 'partial/form.html' with value_submit='Add publication' form_method='post' enctype='multipart/form-data' %}
{% endblock %}